import state

es={
    # Language
    "lang": "Por favor selecciona un idioma",
    # Instructions
    "instructions": "Puedes usar el ratón (click)",
    "instructions2": "o el teclado (ENTER) para seleccionar",
    "instructions3": "INSTRUCCIONES",
    "instructions4": "Todo el juego funciona tanto con ratón (CURSOR+CLICK) ",
    "instructions5": "como con teclado (FLECHAS + ENTER o ESPACIO) para seleccionar,",
    "instructions6": " en el caso de los códigos debe utilizarse el teclado.",
    "instructions7": "Para salir de diálogos presiona ESC.",
    "instructions8": "Para activar/desactivar pantalla completa presiona a la vez R+A+U+L.",
    # Menu
    "menu": "Presiona cualquier tecla para empezar",
    "char": "Selecciona un personaje",
    "name": "Introduce tu nombre y presiona ENTER",
    "max": "(8 letras max)",
    # Scenes
    "boss": "Jefe",
    "boss1": "Me alegra que hayas venido tan rápido, {player}./n Sabía que podía contar contigo para algo así.",
    "boss2": "Tenemos una situación un tanto... particular.",
    "boss3": "Hemos detectado patrones poco usuales en uno de los perfiles que llevábamos meses rastreando.",
    "boss4": "Necesitamos saber todo sobre este sujeto. Queremos ver si puede unirse a nosotros.",
    "boss5": "Tu misión es sencilla, queremos que entres en su casa y encuentres datos sobre sus capacidades.",
    "boss6": "Esta vez tu misión será individual. Si sale mal, ni siquiera nosotros reconoceremos que estuviste ahí.",
    "boss7": "Buena suerte, {player}./n Sabes dónde encontrarme... ",
    "house1": "Sales a la misión con el objetivo claro.",
    "house2": "Encontrarás todo lo que oculte este sujeto...",
    "house3": "Esta debe de ser su casa, entro.",
    # Selections
    "selec": "Dejarlo",
    "selec1": "Ver",
    "selec2": "Abrir",
    "selec3": "Jugar",
    "selec4": "Cambiar",
    # Bedroom
    "box_open": "¡Se ha abierto la caja!",
    "box_opened": "Una extraña caja. Parece abierta.",
    "box_closed": "Una extraña caja. Parece cerrada.",
    "box_blue": "Hace falta la llave AZUL.",
    "box_red": "Hace falta la llave ROJA.",
    "box_green": "Hace falta la llave VERDE.",
    "box_yellow": "Hace falta la llave AMARILLA.",
    "box_clue": "Hay un papel con indicaciones en su interior. ",
    "box_clue1": "La caja fuerte es como siempre: 1-Pelota 2-Juego 3-Musica 4-Tomate. ",
    "clothes": "Entre su ropa hay 2 trajes y 1 mochila de Deloitte, debió de ser consultor un tiempo.",
    # Living
    "basketball": "Parece que al sujeto le gusta el baloncesto.",
    "basketball1": "Es una pelota original de la NBA, solamente pone que es la talla 7.",
    "safe": "Hay una caja fuerte en la pared.",
    "safe1": "INTRODUCE EL CÓDIGO:",
    "safe2": "Código incorrecto.",
    "safe3": "click",
    "button1": "Se ha oído un ruido en otra habitación, creo que algo ha cambiado.",
    "pictures1": "Hay 9 fotografias en la pared.",
    "pictures2": "Son fotos de viajes con varios amigos.",
    # Gaming
    "gameballs1": "Hay un videojuego encendido. ",
    "gameballs2": "PUNTUACION A SUPERAR: 6. ",
    "gameballs3": "Se ha acabado la partida y se ve el número 4 en la pantalla.",
    "START":"EMPEZAR",
    "difficulty": "Dificultad:  ",
    "low":"baja",
    "escape":"Presiona ESC para salir",
    "space":"Presiona ESPACIO para reintentar",
    "code": "Parece que se dejó ejecutando un archivo en Python sobre optimización matemática. ",
    # Studio
    "rollers": "Unos patines bastante gastados de la talla 47.",
    "rollers1": "Se nota que han recorrido kilómetros, debe utilizarlos a menudo.",
    "music": "Interesante, hay 6 canciones preparadas...",
    "books": "Hay novelas fantásticas y libros filosóficos o de pensamiento crítico mezclados.",
    # Kitchen
    "list": "La lista de la compra.",
    "list1": "Tomate x1, mozzarella x5, masa de pizza x3, jamón york x8, tomate x2 y tomate x5.",
    "fridge": "¿Habrá algo dentro de la nevera?",
    "fridge1": "Todo rojo...",
    # Basement
    "basement": "*TOC, TOC*",
    "basement1": "Sabía que venías, pero no me esperaba que llegases hasta aquí.",
    "basement2": "Por si no queda claro, las paredes lo gritan.",
    "basement3": "Soy el sujeto, pero...¿Quién soy?",
    "basement4": "Así no...",
    # End
    "end1": "Felicidades, lo has hecho mucho mejor de lo que me esperaba.",
    "end2": "Aunque él no lo sabe, tengo a tu jefe y a toda la organización vigilados, por eso sabía que vendrías.",
    "end3": "Dicho esto, creo que queda claro que estoy más que capacitado para trabajar con vosotros.",
    "end4": "Espero que hayas disfrutado de este camino y que no te haya hecho perder mucho tiempo.",
    "end5": "Para la próxima vez, si presionas H+I+R+E+D a la vez llegarás directamente a esta sala.",
    "end6": "Espero saber de ti pronto, pero por favor, sal ya de mi casa.",
}

en = {
    # Language
    "lang": "Please select a language",
    # Instructions
    "instructions": "You can use the mouse (click)",
    "instructions2": " or the keyboard (ENTER) to select",
    "instructions3": "INSTRUCTIONS",
    "instructions4": "The game can be played using either the mouse (CURSOR + CLICK)",
    "instructions5": "or the keyboard (ARROWS + ENTER or SPACE) to select,",
    "instructions6": " in the case of codes, the keyboard must be used.",
    "instructions7": "To exit dialogues press ESC.",
    "instructions8": "To enable/disable fullscreen, press R+A+U+L simultaneously.",
    # Menu
    "menu": "Press any key to start",
    "char": "Choose a character",
    "name": "Enter your name and press ENTER",
    "max": "(8 letters max)",
    # Scenes
    "boss": "Boss",
    "boss1": "I'm glad you came so quickly, {player}./n I knew I could count on you for something like this.",
    "boss2": "We have a rather... peculiar situation.",
    "boss3": "We've detected unusual patterns in one of the profiles we've been tracking for months.",
    "boss4": "We need to know everything about him. See if he could join us.",
    "boss5": "Your mission is simple: we want you to enter his house and find data about his abilities.",
    "boss6": "This time your mission will be solo. If it goes wrong, we won't acknowledge you were there.",
    "boss7": "Good luck, {player}./n You know where to find me... ",
    "house1": "You head out on your mission with a clear goal.",
    "house2": "You'll find everything this subject is hiding...",
    "house3": "This must be his house. I'm going in.",
    # Selections
    "selec": "Leave it",
    "selec1": "Look",
    "selec2": "Open",
    "selec3": "Play",
    "selec4": "Change",
    # Bedroom
    "box_open": "The box has opened!",
    "box_opened": "A strange box. Seems to be open.",
    "box_closed": "A strange box. Seems to be closed.",
    "box_blue": "The BLUE key is needed.",
    "box_red": "The RED key is needed.",
    "box_green": "The GREEN key is needed.",
    "box_yellow": "The YELLOW key is needed.",
    "box_clue": "There's a paper with clues inside.",
    "box_clue1": "The safe is as always: 1-Ball 2-Game 3-Music 4-Tomato.",
    "clothes": "Among his clothes there are 2 suits and 1 Deloitte backpack. He must have worked as a consultant for a while.",
    # Living
    "basketball": "Seems like the subject enjoys basketball.",
    "basketball1": "It's an official NBA ball, only says it's size 7.",
    "safe": "There is a safe on the wall.",
    "safe1": "ENTER THE CODE:",
    "safe2": "Wrong code.",
    "safe3": "click",
    "button1": "A sound came from another room. I think something changed.",
    "pictures1": "There are 9 photographs on the wall.",
    "pictures2": "They're travel photos with different friends.",
    # Gaming
    "gameballs1": "There's a videogame turned on.",
    "gameballs2": "SCORE TO BEAT: 6. ",
    "gameballs3": "The game ended, and the number 4 is displayed on screen.",
    "START": "START",
    "difficulty": "Difficulty:  ",
    "low": "low",
    "escape": "Press ESC to exit",
    "space": "Press SPACE to retry",
    "code": "Looks like he left a Python file running about mathematical optimization.",
    # Studio
    "rollers": "Worn-out rollerblades, size 47.",
    "rollers1": "You can tell they've gone many kilometers. He must use them often.",
    "music": "Interesting, there are 6 songs prepared...",
    "books": "There are fantasy novels and books on philosophy or critical thinking all mixed together.",
    # Kitchen
    "list": "The shopping list.",
    "list1": "Tomato x1, mozzarella x5, pizza dough x3, ham x8, tomato x2, and tomato x5.",
    "fridge": "Could there be something in the fridge?",
    "fridge1": "All red...",
    # Basement
    "basement": "*KNOCK, KNOCK*",
    "basement1": "I knew you were coming, but I didn't expect you to make it this far.",
    "basement2": "Just in case it's not clear, the walls scream it.",
    "basement3": "I'm the subject, but... who am I?",
    "basement4": "Not like this...",
    # End
    "end1": "Congratulations, you've done much better than I expected.",
    "end2": "Although he doesn't know it, I'm watching your boss and the entire organization — that's how I knew you'd come.",
    "end3": "That said, I think it's clear I'm more than qualified to work with you.",
    "end4": "I hope you enjoyed the journey and that I didn't waste too much of your time.",
    "end5": "Next time, if you press H+I+R+E+D at the same time, you'll come straight to this room.",
    "end6": "I hope to hear from you soon, but please, get out of my house.",
}
